spring:
  datasource:
    url: ${APP_DB_URL}
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: validate

app:
  kafka:
    bootstrap-servers: ${APP_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      transaction-id-prefix: tx-
      properties:
        enable.idempotence: true
    consumer:
      group-id: edd_krm
      enable-auto-commit: false
      isolation-level: read_committed
